### ISSUE TITLE
Compilation issues -- can't find edgelist2csr; adj2csr;

### ISSUE THREAD

**Issue by Penny-Zhang-9051** [ZhengChenCS/CompressGraph#1]
Hello,

I tried to reproduce the program. Here is an issue, I have found cmake file in utils directory but that is not included in the original cmake file.

I try to compile the program in ubuntu 20.04 I can successfully run:  'compress' ;  'filter'; and find 'convert2binary' ; however, there is no executables beside edgelist2csr ;adj2csr;

Based on the situation, I am not so sure if it is caused by Compilation issues.

Thank you for your time and looking forward to hearing from you!

Sincerely,

Penny

**Comment by ZhengChenCS** [comment]
Hello,

Thanks for your reminding, I have updated the cmake file.
I hope this can help you.

Zheng
